---
- name: set command alias
  become: false
  git_config:
    name: alias.{{ item.alias }}
    scope: global
    value: "{{ item.cmd }}"
  with_items:
    - { cmd: commit, alias: ci }
    - { cmd: status, alias: st }
    - { cmd: checkout, alias: co }
    - { cmd: branch, alias: br }

 
- name: set git editor
  become: false
  git_config:
    name: core.editor
    scope: global
    value: vim


- name: set user info
  become: false
  git_config:
    name: user.{{ item.name }}
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: email, value: 'hanfeng@zdns.cn' }
    - { name: name, value: 'hanfeng' }
